@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

frame "reference" {
  entity "application_send_logs" {
    + application_send_log_id: INT <<Gen>>
    ==
    sent_at: DATETIME
    # contract_id: INT
    created_by: INT
  }
  entity "demand_letter_send_logs" {
    + demand_letter_send_log_id: INT <<Gen>>
    ==
    sent_at: DATETIME
    # contract_id: MEDIUMINT
    # invoice_id: INT
    created_by: INT
  }
  entity "journalizings" {
    + journalizing_id: INT <<Gen>>
    ==
    yearmonth: INT
    journalizing_type: TINYINT
    # invoice_detail_id: INT
    from: DATE
    unit_price: INT
    payment_date: DATE
    payment_amount: INT
    payment_count: TINYINT
    payment_status: SMALLINT
    created_at: DATETIME
    created_by: INT
  }
  entity "schedule_adjustment_requests" {
    + schedule_adjustment_request_id: INT <<Gen>>
    ==
    received_at: DATETIME
    # maintenance_schedule_id: INT
    # contract_id: INT
    # note_user_id: INT
    original_maintenance_date: DATE
    request_maintenance_date: DATE
    status: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "schedule_mail_send_logs" {
    + schedule_mail_log_id: INT <<Gen>>
    ==
    sent_at: DATETIME
    # contract_id: INT
    created_by: INT
  }
  entity "statement_of_delivery_send_log_details" {
    + statement_of_delivery_send_log_id: INT
    + maintenance_id: INT
    ==
    skip_collect_amount: TINYINT
    created_at: DATETIME
    created_by: INT
  }
  entity "statement_of_delivery_send_logs" {
    + statement_of_delivery_send_log_id: INT <<Gen>>
    ==
    sent_at: DATETIME
    mailbody: TEXT
    # contract_id: INT
    maintenance_date: DATE
    next_maintenance_date: DATE
    created_by: INT
  }
  entity "tft_donation_requests" {
    + tft_donation_request_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    from_tft: DATE
    to_tft: DATE
    from_term: DATE
    to_term: DATE
    quantity: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }

  entity "notice_templates" {
    + notice_template_id: INT <<Gen>>
    ==
    name: VARCHAR
    content: TEXT
    service_type: INT
    is_display: TINYINT
    sort_order: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "prefectures" {
    + prefecture_id: INT <<Gen>>
    ==
    name: VARCHAR
    delivery_dates: SMALLINT∂
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "taxes" {
    + tax_id: INT <<Gen>>
    ==
    from: DATE
    to: DATE
    rate: DECIMAL
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "tkvs" {
    + tkv_id: INT <<Gen>>
    ==
    type: VARCHAR
    key: VARCHAR
    value: TEXT
    description: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "delivery_results_changes_histories" {
    + delivery_results_changes_history_id: INT <<Gen>>
    ==
    prev_maintenance_id: INT
    next_maintenance_id: INT
    created_at: DATETIME
    created_by: INT
  }
}
frame "users ERD" {
  entity "users_clients" {
    + id: INT  <<Gen>>
    ==
    name: VARCHAR
    # client_id: VARCHAR
    client_secret: VARCHAR
    redirect_uri: VARCHAR
    auto_approve: TINYINT
    autonomous: TINYINT
    status: ENUM
    suspended: TINYINT
    notes: TINYTEXT
  }
  entity "users_sessions" {
    + id: INT <<Gen>>
    ==
    # client_id: VARCHAR
    redirect_uri: VARCHAR
    type_id: VARCHAR
    type: ENUM
    code: TEXT
    access_token: VARCHAR
    stage: ENUM
    first_requested: INT
    last_updated: INT
    limited_access: TINYINT
  }
  entity "users_sessionscopes" {
    + id: INT <<Gen>>
    ==
    # session_id: INT
    access_token: VARCHAR
    # scope: VARCHAR
  }
  entity "users_scopes" {
    + id: INT <<Gen>>
    ==
    # scope: VARCHAR
    name: VARCHAR
    description: VARCHAR
  }
  users_clients |o.d.o{  users_sessions
  users_sessions |o.r.o{  users_sessionscopes
  users_scopes |o.d.o{  users_sessionscopes
  entity "users_user_roles" {
    + user_id: INT
    + role_id: INT
    ==
  }
  entity "users_permissions" {
    + id: INT <<Gen>>
    ==
    area: VARCHAR
    permission: VARCHAR
    description: VARCHAR
    actions: TEXT
    # user_id: INT
    created_at: INT
    created_by: INT
    updated_at: INT
    updated_by: INT
  }
  entity "users_metadata" {
    + id: INT <<Gen>>
    ==
    # parent_id: INT
    key: VARCHAR
    value: VARCHAR
    # user_id: INT
    created_at: INT
    updated_at: INT
  }
  entity "users_providers" {
    + id: INT <<Gen>>
    ==
    # parent_id: INT
    provider: VARCHAR
    uid: VARCHAR
    secret: VARCHAR
    access_token: VARCHAR
    expires: INT
    refresh_token: VARCHAR
    # user_id: INT
    created_at: INT
    updated_at: INT
  }
  entity "users_group_roles" {
    + group_id: INT
    + role_id: INT
    ==
  }
  entity "users_role_permissions" {
    + id: INT <<Gen>>
    ==
    # role_id: INT
    # perms_id: INT
    actions: TEXT
  }
  entity "users_roles" {
    + id: INT <<Gen>>
    ==
    name: VARCHAR
    filter: ENUM
    # user_id: INT
    created_at: INT
    created_by: INT
    updated_at: INT
    updated_by: INT
  }
  entity "users_groups" {
    + id: INT <<Gen>>
    ==
    name: VARCHAR
    # user_id: INT
    created_at: INT
    updated_at: INT
  }
  entity "users" {
    + id: INT <<Gen>>
    ==
    username: VARCHAR
    password: VARCHAR
    # group_id: INT
    email: VARCHAR
    last_login: VARCHAR
    previous_login: VARCHAR
    login_hash: VARCHAR
    user_id: INT
    created_at: INT
    updated_at: INT
  }
  users }|.l.|| users_metadata
  users }|.r.|| users_providers
  users }|.d.|| users_permissions
  users ||..|{ users_user_roles
  users_roles ||.r.|{ users_user_roles
  users_roles ||.d.|{ users_group_roles
  users_group_roles }|.r.|| users_groups
  users_metadata ||..|{ users_metadata
  users_providers ||..|{ users_providers
  users_role_permissions }|..|| users_roles
  users_permissions ||.d.|{ users_role_permissions
  entity "users_user_permissions" {
    + id: INT <<Gen>>
    ==
    # user_id: INT
    # perms_id: INT
    actions: TEXT
  }
  entity "users_group_permissions" {
    + id: INT <<Gen>>
    ==
    # group_id: INT
    # perms_id: INT
    actions: TEXT
  }
}
frame "plans ERD" {
  entity "office_addon_types" {
    + office_addon_type_id: TINYINT <<Gen>>
    ==
    office_addon_type_name: VARCHAR
    created_at: DATETIME
    created_by: INT
  }
  entity "office_option_types" {
    + office_option_type_id: TINYINT <<Gen>>
    ==
    office_option_type_name: VARCHAR
    created_at: DATETIME
    created_by: INT
  }
  entity "office_addon_order_send_logs" {
    + office_addon_order_send_log_id: INT <<Gen>>
    ==
    # office_addon_order_id: INT
    sent_at: DATETIME
    mailbody: TEXT
    contract_id: INT
    created_by: INT
  }
  entity "office_addon_orders" {
    + office_addon_order_id: INT <<Gen>>
    ==
    # contract_id: INT
    # office_addon_id: INT
    maintenance_date: DATE
    from: DATE
    text: TEXT
    inner_memo: TEXT
    registered_at: DATETIME
    registered_by: INT
    reserved_at: DATETIME
    reserved_by: INT
    status: TINYINT
    is_deleted: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "office_addons" {
    + office_addon_id: SMALLINT <<Gen>>
    ==
    service_type: TINYINT
    # office_addon_type_id: TINYINT
    name: VARCHAR
    inner_name: VARCHAR
    inner_short_name: VARCHAR
    invoice_name: VARCHAR
    invoice_short_name: VARCHAR
    quantity_limit: SMALLINT
    price: MEDIUMINT
    tax_class: TINYINT
    maintenance_count: TINYINT
    operation_times: SMALLINT
    sort_order: MEDIUMINT
    is_deleted: TINYINT
    * zuora_product_rate_plan_id: VARCHAR
    * zuora_product_rate_plan_charge_id: VARCHAR
    zuora_sync_status: INT
    zuora_sync_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "office_option_groups" {
    + office_option_group_id: SMALLINT <<Gen>>
    ==
    service_type: TINYINT
    # office_option_type_id: TINYINT
    name: VARCHAR
    inner_name: VARCHAR
    inner_short_name: VARCHAR
    invoice_name: VARCHAR
    invoice_short_name: VARCHAR
    sort_order: MEDIUMINT
    is_deleted: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "office_options" {
    + office_option_id: SMALLINT <<Gen>>
    ==
    # office_option_group_id: SMALLINT
    # office_plan_id: SMALLINT
    quantity_limit: SMALLINT
    price: MEDIUMINT
    tax_class: TINYINT
    maintenance_count: TINYINT
    operation_times: SMALLINT
    is_deleted: TINYINT
    block_split_group: TINYINT
    block_discount_office_option_id: SMALLINT
    * zuora_product_rate_plan_id: VARCHAR
    * zuora_product_rate_plan_charge_id: VARCHAR
    zuora_sync_status: INT
    zuora_sync_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "office_plan_order_send_logs" {
    + office_plan_order_send_log_id: INT <<Gen>>
    ==
    # office_plan_order_id: INT
    sent_at: DATETIME
    mailbody: TEXT
    contract_id: INT
    created_by: INT
  }
  entity "office_plan_orders" {
    + office_plan_order_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    # office_plan_id: SMALLINT
    current_office_plan_id: SMALLINT
    from: DATE
    to: DATE
    invoice_cycle: TINYINT
    contract_renewal_cycle: TINYINT
    price_e_pattern: TINYINT
    inner_memo: TEXT
    memo: TEXT
    reason: TEXT
    status: TINYINT
    is_deleted: TINYINT
    order_type: TINYINT
    published_at: DATETIME
    published_by: INT
    application_at: DATETIME
    application_by: INT
    registered_at: DATETIME
    registered_by: INT
    reserved_at: DATETIME
    reserved_by: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "office_plans" {
    + office_plan_id: SMALLINT <<Gen>>
    ==
    service_type: TINYINT
    name: VARCHAR
    inner_name: VARCHAR
    inner_short_name: VARCHAR
    invoice_name: VARCHAR
    invoice_short_name: VARCHAR
    quantity_limit: SMALLINT
    price: MEDIUMINT
    tax_class: TINYINT
    maintenance_count: TINYINT
    operation_times: SMALLINT
    sort_order: MEDIUMINT
    is_deleted: TINYINT
    weight: INT
    uncollected_rate: DECIMAL
    is_new_plan: TINYINT
    office_addon_id: SMALLINT
    office_addon_block_split_group: TINYINT
    * zuora_product_rate_plan_id: VARCHAR
    * zuora_product_rate_plan_charge_id: VARCHAR
    zuora_sync_status: INT
    zuora_sync_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "plan_revision_logs" {
    + plan_revision_log_id: INT <<Gen>>
    ==
    # contract_id: INT
    # plan_id: INT
    created_by: INT
  }
  entity "plan_revision_send_logs" {
    + plan_revision_send_log_id: INT <<Gen>>
    ==
    # contract_id: INT
    yearmonth: INT
    sent_at: DATETIME
    downloaded_at: DATETIME
    created_by: INT
  }
  entity "plans" {
    + plan_id: SMALLINT <<Gen>>
    ==
    plan_type: TINYINT
    name: VARCHAR
    inner_name: VARCHAR
    inner_short_name: VARCHAR
    quantity_limit: SMALLINT
    price: MEDIUMINT
    tax_class: TINYINT
    maintenance_count: TINYINT
    operation_times: SMALLINT
    service_type: TINYINT
    chart_color: VARCHAR
    sort_order: SMALLINT
    is_deleted: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "invoice_plans" {
    + invoice_plan_id: INT <<Gen>>
    ==
    # plan_id: SMALLINT
    invoice_plan_type: TINYINT
    name: VARCHAR
    invoice_name: VARCHAR
    quantity_limit: SMALLINT
    price: MEDIUMINT
    tax_class: TINYINT
    sort_order: SMALLINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  plans |o.r.o{ invoice_plans
  plans |o.d.o| office_plans
  plans |o.u.o{ plan_revision_logs
  office_plans |o.d.o{ office_options
  office_options }o.l.o| office_option_groups
  office_option_groups }o.u.o| office_option_types
  office_addon_orders }o.d.o| office_addons
  office_addons }o.d.o| office_addon_types
  office_addon_types |o.d.o{ office_addon_order_send_logs
  office_plan_orders |o.d.o{ office_plan_order_send_logs
  plans |o.d.o| office_plans
  plans |o.u.o{ plan_revision_logs
  office_plans |o.d.o{ office_options
  office_options }o.l.o| office_option_groups
  office_option_groups }o.u.o| office_option_types
  office_addon_orders }o.d.o| office_addons
  office_addons }o.d.o| office_addon_types
  office_addon_types |o.d.o{ office_addon_order_send_logs
  office_plan_orders |o.d.o{ office_plan_order_send_logs
}
frame "company ERD" {
  entity "companies" {
    + company_id: MEDIUMINT <<Gen>>
    ==
    name: VARCHAR
    name_kana: VARCHAR
    is_monitoring: TINYINT
    payment_type: TINYINT
    payment_type_registered_at: DATE
    ceo_name: VARCHAR
    ceo_name_kana: VARCHAR
    ceo_post: VARCHAR
    zipcode: VARCHAR
    address_prefecture: TINYINT
    address_city: VARCHAR
    address_street_number: VARCHAR
    address_after: VARCHAR
    tel: VARCHAR
    fax: VARCHAR
    crm_account_id: VARCHAR
    * zuora_parent_account_number: VARCHAR
    zuora_sync_status: TINYINT
    zuora_sync_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "company_extents" {
    + company_id: MEDIUMINT <<Gen>>
    ==
    contact_memo: TEXT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contacts" {
    + contact_id: INT <<Gen>>
    ==
    # company_id: MEDIUMINT
    name: VARCHAR
    name_kana: VARCHAR
    email: VARCHAR
    tel: VARCHAR
    fax: VARCHAR
    mobile: VARCHAR
    memo: VARCHAR
    department_name: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "mapping_companies_contacts" {
    + mapping_companies_contacts_id: INT <<Gen>>
    ==
    # contact_id: INT
    email_purpose_id: TINYINT
    type: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "mapping_contracts_addons" {
    + mapping_contracts_addons_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: INT
    # plan_id: INT
    from: DATE
    to: DATE
    invoice_month: INT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "mapping_contracts_contacts" {
    + mapping_contracts_contacts_id: INT <<Gen>>
    ==
    # contract_id: INT
    # contact_id: INT
    email_purpose_id: TINYINT
    type: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "mapping_contracts_plans" {
    + mapping_contracts_plans_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: INT
    # plan_id: INT
    from: DATE
    to: DATE
    invoice_cycle: TINYINT
    contract_renewal_cycle: TINYINT
    current_contract_period: SMALLINT
    initial_contract_period: TINYINT
    price_e_pattern: TINYINT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contract_delivery_available_hours" {
    + id: INT <<Gen>>
    ==
    specified_time_start: TIME
    specified_time_end: TIME
    contract_id: MEDIUMINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contract_delivery_dates" {
    + contract_id: MEDIUMINT
    ==
    is_deliverable_mon: TINYINT
    is_deliverable_tue: TINYINT
    is_deliverable_wed: TINYINT
    is_deliverable_thu: TINYINT
    is_deliverable_fri: TINYINT
    is_deliverable_holiday: TINYINT
    start_time: TIME
    end_time: TIME
    operation_times: SMALLINT
    operation_times_comment: TEXT
    parking_times: SMALLINT
    parking_times_comment: TEXT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contract_delivery_locations" {
    + contract_id: MEDIUMINT
    ==
    zipcode: VARCHAR
    address_prefecture: TINYINT
    address_city: VARCHAR
    address_street_number: VARCHAR
    address_after: VARCHAR
    area_id: TINYINT
    car_park: TINYINT
    how_to_use_built_in_car_park: VARCHAR
    near_by_car_park: VARCHAR
    receiption_floor: VARCHAR
    entrance_exit_memo: VARCHAR
    inside_building_memo: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contract_delivery_okanbins" {
    + contract_id: MEDIUMINT
    ==
    stuff_name: VARCHAR
    email_address: VARCHAR
    delivery_time: INT
    bowl: VARCHAR
    one_plate: VARCHAR
    chopsticks: VARCHAR
    spoon: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contract_extents" {
    + contract_id: MEDIUMINT
    ==
    from_tft: DATE
    to_tft: DATE
    maintenance_count_comment: VARCHAR
    cs_memo: TEXT
    first_maintenance_memo: TEXT
    collective_registration_memo: TEXT
    employee_number: INT
    industry_type: TINYINT
    tel: VARCHAR
    transfer_information: VARCHAR
    is_accepted_request_alert: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contract_sales_accumulations" {
    + contract_id: MEDIUMINT
    yearmonth: INT
    ==
    sales_amount: INT
    collect_amount: INT
    total_sales_amount: INT
    total_uncollect_amount: INT
    amortization_amount: INT
    billing_diff: INT
    billing_reason: TINYINT
    carry_over_total_uncollect_amount: INT
    uncollected_rate: DECIMAL
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts" {
    + contract_id: MEDIUMINT <<Gen>>
    ==
    name: VARCHAR
    name_kana: VARCHAR
    short_place_name: VARCHAR
    company_id: MEDIUMINT
    application_date: DATE
    first_maintenance_date: DATE
    first_date: DATE
    first_date_calc: DATE
    start_day: TINYINT
    initial_start_day: TINYINT
    expire_date: DATE
    last_maintenance_date: DATE
    irregular_payments: VARCHAR
    need_invoice_mailing: TINYINT
    is_company_pay: TINYINT
    maintenance_count: TINYINT
    service_type: TINYINT
    registration_status: TINYINT
    initial_office_plan_id: SMALLINT
    payment_terms: TINYINT
    invoice_pattern: TINYINT
    auto_renewal_flag: TINYINT
    * zuora_account_id: VARCHAR
    * zuora_subscription_id: VARCHAR
    zuora_diff_charge_id: VARCHAR
    zuora_offset_charge_id: VARCHAR
    crm_account_id: VARCHAR
    zuora_subscription_number: VARCHAR
    zuora_child_account_number: VARCHAR
    zuora_sync_status: TINYINT
    zuora_sync_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_cs_tags" {
    + contracts_cs_tag_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: INT
    cs_tag_id: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_office_addons" {
    + contracts_office_addon_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    office_addon_id: SMALLINT
    from: DATE
    to: DATE
    invoice_month: INT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_office_addons_histories" {
    + contracts_office_addons_history_id: INT <<Gen>>
    ==
    logged_at: DATETIME
    # contracts_office_addon_id: MEDIUMINT
    # contract_id: MEDIUMINT
    office_addon_id: SMALLINT
    from: DATE
    to: DATE
    invoice_month: INT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_office_options" {
    + contracts_office_option_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    office_option_id: SMALLINT
    term_group_id: MEDIUMINT
    from: DATE
    to: DATE
    initial_contract_period: TINYINT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_office_options_histories" {
    + contracts_office_options_history_id: INT <<Gen>>
    ==
    logged_at: DATETIME
    # contracts_office_option_id: MEDIUMINT
    # contract_id: MEDIUMINT
    office_option_id: SMALLINT
    term_group_id: MEDIUMINT
    from: DATE
    to: DATE
    initial_contract_period: TINYINT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_office_plans" {
    + contracts_office_plan_id: MEDIUMINT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    office_plan_id: SMALLINT
    term_group_id: MEDIUMINT
    from: DATE
    to: DATE
    initial_contract_period: TINYINT
    invoice_cycle: TINYINT
    contract_renewal_cycle: TINYINT
    price_e_pattern: TINYINT
    is_trial: TINYINT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_office_plans_histories" {
    + contracts_office_plans_history_id: INT <<Gen>>
    ==
    logged_at: DATETIME
    # ccontracts_office_plan_id: MEDIUMINT
    # ccontract_id: MEDIUMINT
    office_plan_id: SMALLINT
    term_group_id: MEDIUMINT
    from: DATE
    to: DATE
    initial_contract_period: TINYINT
    invoice_cycle: TINYINT
    contract_renewal_cycle: TINYINT
    price_e_pattern: TINYINT
    is_trial: TINYINT
    application_date: DATE
    recorded_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "contracts_unreceivable_dates" {
    + contracts_unreceivable_date_id: INT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    unreceivable_date: DATE
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "cs_tags" {
    + cs_tag_id: INT  <<Gen>>
    ==
    name: VARCHAR
    is_display: TINYINT
    service_type: TINYINT
    sort_order: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "auto_renewal_contracts_office_options" {
    + contract_id: INT
    + term_group_id: INT
    ==
    created_at: DATETIME
    created_by: INT
  }
  entity "note_restrictable_functions" {
    + note_restrictable_function_id: INT <<Gen>>
    ==
    function_name: VARCHAR
    sort_order: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "mapping_contracts_note_restrictable_functions" {
    + mapping_contracts_note_restrictable_function_id: INT <<Gen>>
    ==
    # contract_id: INT
    # note_restrictable_function_id: INT
    created_at: DATETIME
    created_by: INTßß
  }
  frame "contract temp" {
    entity "tmp_contracts" {
      + contract_id: MEDIUMINT <<Gen>>
      ==
      name: VARCHAR
      name_kana: VARCHAR
      short_place_name: VARCHAR
      company_id: MEDIUMINT
      application_date: DATE
      first_maintenance_date: DATE
      first_date: DATE
      first_date_calc: DATE
      start_day: TINYINT
      initial_start_day: TINYINT
      expire_date: DATE
      last_maintenance_date: DATE
      irregular_payments: VARCHAR
      need_invoice_mailing: TINYINT
      is_company_pay: TINYINT
      maintenance_count: TINYINT
      service_type: TINYINT
      registration_status: TINYINT
      initial_office_plan_id: SMALLINT
      payment_terms: TINYINT
      invoice_pattern: TINYINT
      auto_renewal_flag: TINYINT
      * zuora_account_id: VARCHAR
      * zuora_subscription_id: VARCHAR
      zuora_diff_charge_id: VARCHAR
      zuora_offset_charge_id: VARCHAR
      crm_account_id: VARCHAR
      zuora_subscription_number: VARCHAR
      zuora_child_account_number: VARCHAR
      zuora_sync_status: TINYINT
      zuora_sync_at: DATETIME
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    entity "contract_cycles" {
      + mapping_contracts_plans_id: INT <<Gen>>
      ==
      from: DATE
      to: DATE
    }
  }
  companies ||.u.o| company_extents
  companies ||.u.o{ contacts
  companies |o.d.o| contracts
  contacts |o.u.o{ mapping_companies_contacts
  contacts |o..o{ mapping_contracts_contacts
  mapping_contracts_contacts }o.r.o| contracts
  contracts |o.u.o{ contracts_cs_tags
  contracts_cs_tags }o.u.|| cs_tags
  contracts |o.l.o{ auto_renewal_contracts_office_options
  contracts |o.l.o{ mapping_contracts_plans
  contracts |o.l.o{ mapping_contracts_addons
  contracts |o..o| contract_delivery_dates
  contracts |o..o| contract_delivery_locations
  contracts |o..o| contract_delivery_okanbins
  contracts |o..o| contract_extents
  contracts |o..o| contract_sales_accumulations
  contracts |o..o{ contract_delivery_available_hours
  contracts |o..o{ contracts_unreceivable_dates
  contracts |o..o{ contracts_office_addons
  contracts |o..o{ contracts_office_plans
  contracts |o..o{ contracts_office_options
  contracts_office_addons ||..o{ contracts_office_addons_histories
  contracts_office_plans ||..o{ contracts_office_plans_histories
  contracts_office_options ||..o{ contracts_office_options_histories
  note_restrictable_functions |o..o{ mapping_contracts_note_restrictable_functions
  contracts |o.d.o{ mapping_contracts_note_restrictable_functions
}
frame "admins ERD" {
  entity "admins" {
    + id: INT  <<Gen>>
    ==
    * email: VARCHAR
    encrypted_password: VARCHAR
    name: VARCHAR
    password_expiration_at: DATETIME
    *reset_password_token: VARCHAR
    reset_password_sent_at: DATETIME
    remember_created_at: DATETIME
    locked_at: DATETIME
    sign_in_count: INT
    current_sign_in_at: DATETIME
    last_sign_in_at: DATETIME
    current_sign_in_ip: VARCHAR
    last_sign_in_ip: VARCHAR
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "mapping_admins_roles" {
    + admin_id: INT
    + role_id: INT
  }
  entity "roles" {
    + role_id: INT <<Gen>>
    ==
    name: VARCHAR
    description: VARCHAR
    sort_order: INT
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "area_groups" {
    + area_group_id: INT <<Gen>>
    ==
    * area_group_name: VARCHAR
    service_type: TINYINT
    is_recommend_mon: TINYINT
    is_recommend_tue: TINYINT
    is_recommend_wed: TINYINT
    is_recommend_thu: TINYINT
    is_recommend_fri: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "areas" {
    + area_id: INT <<Gen>>
    ==
    # area_group_id: TINYINT
    * area_name: VARCHAR
    is_display: TINYINT
    is_without_23_ward: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "calendar_extents" {
    + date: DATE
    ==
    maintenance_memo: TEXT
    delivery_line_count: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "calendars" {
    + date: DATE
    ==
    date_type: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "faq_categories" {
    + faq_category_id: SMALLINT <<Gen>>
    ==
    faq_category_name: VARCHAR
    sort_order: SMALLINT
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "faqs" {
    + faq_id: INT <<Gen>>
    ==
    # faq_category_id: SMALLINT
    question: VARCHAR
    answer: MEDIUMTEXT
    is_display_note: TINYINT
    is_display_delivery: TINYINT
    sort_order: SMALLINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "information" {
    + information_id: INT <<Gen>>
    ==
    # information_category_id: TINYINT
    service_type: INT
    title: VARCHAR
    body: TEXT
    start_at: DATETIME
    end_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "information_categories" {
    + information_category_id: TINYINT <<Gen>>
    ==
    name: VARCHAR
    sort_order: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "menu_files" {
    + menu_file_id: INT <<Gen>>
    ==
    # menu_id: INT
    service_type: TINYINT
    file_name: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "menus" {
    + menu_id: INT <<Gen>>
    ==
    menu_category_id: SMALLINT
    menu_name: VARCHAR
    start_date: DATE
    end_date: DATE
    request_start_date: DATE
    request_end_date: DATE
    inner_comment: TEXT
    comment: TEXT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "mapping_menus_items" {
    + mapping_menus_item_id: INT <<Gen>>
    ==
    # menu_id: SMALLINT
    # item_id: INT
    is_requestable: TINYINT
    status_id: TINYINT
    sort_order: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  admins |o.d.o{ mapping_admins_roles
  mapping_admins_roles }o..o| roles
  area_groups ||..o{ areas
  calendars ||..o| calendar_extents
  faqs }|..|| faq_categories
  information }|..|| information_categories
  menus ||.u.o{ menu_files
  menus ||.d.o{ mapping_menus_items
}
frame "box ERD" {
  entity "box_continuous_request_shots" {
    + box_id: INT
    + shot_date: DATE
    ==
    comment: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
    shot_time: TIME
  }
  entity "box_continuous_requests" {
    + box_id: INT
    ==
    comment: VARCHAR
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "box_offsets" {
    + box_offset_id: INT <<Gen>>
    ==
    # box_id: INT
    yearmonth: INT
    total_used_amount: MEDIUMINT
    total_used_amount_appli_web: MEDIUMINT
    total_used_amount_appli_native: MEDIUMINT
    total_used_amount_ic: MEDIUMINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "boxes_control_numbers" {
    + boxes_control_numbers_id: INT <<Gen>>
    ==
    # box_id: INT
    control_number: VARCHAR
    settlement_type: TINYINT
    created_at: DATETIME
    created_by: INT
    deleted_at: DATETIME
    deleted_by: INT
  }
  entity "box_stocks" {
    + maintenance_id: INT
    + action_id: TINYINT
    + item_id: INT
    ==
    quantity: MEDIUMINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "box_achievements" {
    + maintenance_id: INT
    + item_id: INT
    ==
    actual_delivery_quantity: INT
    sales_quantity: INT
    loss_quantity: INT
    recall_quantity: INT
    delivery_result_quantity: INT
    stock_quantity: INT
    prepare_quantity: INT
    created_at: DATETIME
  }
  entity "box_orders" {
    + maintenance_id: INT
    + action_id: TINYINT
    + item_id: INT
    ==
    quantity: MEDIUMINT
    created_at: DATETIME
    created_by: INT
  }
  entity "box_prepares" {
    +box_prepare_id: INT <<Gen>>
    ==
    # maintenance_schedule_id: INT
    # box_id: INT
    # item_id: INT
    quantity: MEDIUMINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "boxes" {
    + box_id: INT <<Gen>>
    ==
    # contract_id: INT
    floor: INT
    floor_name: VARCHAR
    is_display_okanpay: TINYINT
    is_itoen: TINYINT
    is_exists: TINYINT
    is_use_collection_box: TINYINT
    storage_type: TINYINT
    rice_box_count: TINYINT
    container_box_count: TINYINT
    one_plate_box_count: TINYINT
    cutter_count: TINYINT
    registration_status: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "box_maintenance_extents" {
    + maintenance_id: INT
    ==
    inner_comment: VARCHAR
    comment: VARCHAR
    power_outage_flg: TINYINT
    moving_flg: TINYINT
    without_maintenance_count_flg: TINYINT
    without_delivery_count_flg: TINYINT
    is_without_delivery_sheet: TINYINT
    is_without_maintenance: TINYINT
    is_without_suggest: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "box_maintenances" {
    + maintenance_id: INT <<Gen>>
    ==
    # maintenance_schedule_id: INT
    # maintenance_date: DATE
    # box_id: INT
    prev_maintenance_id: INT
    notified_at: DATETIME
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "item_continuous_request_shots" {
    + item_continuous_request_id: INT
    + shot_date: DATE
    ==
    # box_id: INT
    # item_id: INT
    quantity: INT
    completion_date: DATE
    is_registered_admin: TINYINT
    is_display_renrakucho: TINYINT
    is_deleted: TINYINT
    is_operated_admin: TINYINT
    operated_at: DATETIME
    operated_by: INT
    accepted_by: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
    shot_time: TIME
  }
  entity "item_continuous_requests" {
    + item_continuous_request_id: INT <<Gen>>
    ==
    # box_id: INT
    # item_id: INT
    quantity: INT
    completion_date: DATE
    is_registered_admin: TINYINT
    is_display_renrakucho: TINYINT
    is_deleted: TINYINT
    is_operated_admin: TINYINT
    operated_at: DATETIME
    operated_by: INT
    accepted_by: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "item_extents" {
    + item_id: INT
    ==
    safety_stock_rate: FLOAT
    min_stock_quantity: MEDIUMINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "item_request_extents" {
    + item_request_id: INT <<Gen>>
    ==
    usage_situation_enquete: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "item_requests" {
    + item_request_id: INT <<Gen>>
    ==
    # maintenance_schedule_id: INT
    # menu_id: SMALLINT
    # box_id: INT
    memo: TEXT
    reflection_date: DATE
    completion_date: DATE
    is_registered_admin: TINYINT
    is_display_renrakucho: TINYINT
    is_deleted: TINYINT
    is_operated_admin: TINYINT
    operated_at: DATETIME
    operated_by: INT
    duplicated_item_request_id: INT
    accepted_by: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "items" {
    + item_id: INT <<Gen>>
    ==
    name: VARCHAR
    middle_name: VARCHAR
    external_name: VARCHAR
    sort_order: INT
    condition_type: INT
    item_sub_type_id: INT
    price_e1: MEDIUMINT
    price_e2: MEDIUMINT
    price_e3: MEDIUMINT
    price_e4: MEDIUMINT
    price_e5: MEDIUMINT
    is_display_logi: TINYINT
    is_display_menu: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "item_conditions" {
    + item_condition_id: SMALLINT
    ==
    name: VARCHAR
    short_name: VARCHAR
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "mapping_item_requests_items" {
    + item_request_id: INT
    + item_id: INT
    ==
    quantity: INT
    created_at: DATETIME
    created_by: INT
  }
  frame "box temp" {
    entity "tmp_boxes" {
      + box_id: INT <<Gen>>
      ==
      # contract_id: INT
      floor: INT
      floor_name: VARCHAR
      is_display_okanpay: TINYINT
      is_itoen: TINYINT
      is_exists: TINYINT
      is_use_collection_box: TINYINT
      storage_type: TINYINT
      rice_box_count: TINYINT
      container_box_count: TINYINT
      one_plate_box_count: TINYINT
      cutter_count: TINYINT
      registration_status: TINYINT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
  }
  entity "box_payments" {
    + maintenance_id: INT
    ==
    used_amount: MEDIUMINT
    collect_amount: MEDIUMINT
    collect_amount_cash: MEDIUMINT
    collect_amount_appli_web: MEDIUMINT
    collect_amount_appli_native: MEDIUMINT
    collect_amount_ic: MEDIUMINT
    uncollect_amount: MEDIUMINT
    created_at: DATETIME
    created_by: INT
  }
  boxes |o.d.o{ item_continuous_requests
  item_continuous_requests }o.d.|| items
  boxes |o.d.o{ box_prepares
  box_prepares }o.d.|| items
  boxes |o.d.o{ item_continuous_request_shots
  item_continuous_request_shots }o.d.|| items
  boxes |o.r.o{ box_maintenances
  box_maintenances ||.r.o| box_payments
  box_maintenances ||.u.o| box_maintenance_extents
  box_maintenances |o.d.o{ statement_of_delivery_send_log_details
  boxes |o.l.o{ boxes_control_numbers
  boxes |o.l.o{ box_offsets
  boxes |o.u.o| box_continuous_request_shots
  boxes |o.u.o| box_continuous_requests
  items ||.l.o| item_extents
  items }o.l.|| item_conditions
  items ||.l.o{ item_requests
  item_requests ||.l.o| item_request_extents
  box_orders }o..|| items
  box_achievements }o..|| items
  box_stocks }o..|| items
  box_maintenances ||..o{ box_achievements
  box_maintenances ||..o{ box_orders
  box_maintenances ||..o{ box_stocks
  entity "item_sub_types" {
    + item_sub_type_id: INT
    ==
    # item_type_id: INT
    item_sub_type_name: VARCHAR
    grouping_flag: TINYINT
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "item_types" {
    + item_type_id: INT
    ==
    sort_order: SMALLINT
    item_type_name: VARCHAR
    created_at: DATETIME
    updated_at: DATETIME
  }
  item_types |o..o{ item_sub_types
  frame "depot" {
    entity "depot_orders" {
      + depot_id: SMALLINT
      + item_id: INT
      + maintenance_date: DATE
      ==
      quantity: MEDIUMINT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    entity "depot_receiveds" {
      + depot_id: SMALLINT
      + item_id: INT
      + maintenance_date: DATE
      ==
      quantity: MEDIUMINT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    entity "depot_stocks" {
      + depot_id: SMALLINT
      + item_id: INT
      + maintenance_date: DATE
      ==
      quantity: MEDIUMINT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    entity "depots" {
      + id: SMALLINT
      ==
      name: VARCHAR
      sales: INT
      area_id: INT
      address: VARCHAR
      phone: VARCHAR
      contact: VARCHAR
      contact_title: VARCHAR
      contact_mail: VARCHAR
      contract_date: DATE
      created_at: INT
      updated_at: INT
    }
    depots |o.u.o{ depot_orders
    depots |o.u.o{ depot_receiveds
    depots |o.u.o{ depot_stocks
  }
  items |o.d.o{ depot_orders
  items |o.d.o{ depot_receiveds
  items |o.d.o{ depot_stocks
  frame "material" {
    entity "mapping_material_requests_materials" {
      + material_request_id: INT
      + material_id: INT
      ==
      quantity: INT
      created_at: DATETIME
      created_by: INT
    }
    entity "material_continuous_request_shots" {
      + material_continuous_request_id: INT
      + shot_date: DATE
      ==
      # box_id: INT
      # material_id: INT
      quantity: INT
      completion_date: DATE
      is_registered_admin: TINYINT
      is_completed_admin: TINYINT
      is_deleted_admin: TINYINT
      deleted_at: DATETIME
      deleted_by: INT
      completed_at: DATETIME
      completed_by: INT
      accepted_by: INT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
      shot_time: TIME
    }
    entity "material_continuous_requests" {
      + material_continuous_request_id: INT <<Gen>>
      ==
      # material_id: INT
      # box_id: INT
      quantity: INT
      completion_date: DATE
      is_registered_admin: INT
      is_completed_admin: TINYINT
      is_deleted_admin: TINYINT
      deleted_at: DATETIME
      deleted_by: INT
      completed_at: DATETIME
      completed_by: INT
      accepted_by: INT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    entity "material_requests" {
      + material_request_id: INT <<Gen>>
      ==
      # maintenance_schedule_id: INT
      # box_id: INT
      reflection_date: DATE
      completion_date: DATE
      is_registered_admin: TINYINT
      is_completed_admin: TINYINT
      is_deleted_admin: TINYINT
      deleted_at: DATETIME
      deleted_by: INT
      completed_at: DATETIME
      completed_by: INT
      accepted_by: INT
      duplicated_material_request_id: INT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    entity "materials" {
      + material_id: INT <<Gen>>
      ==
      name: VARCHAR
      request_unit: INT
      maximum: INT
      maximum_for_big_plan: INT
      created_at: DATETIME
      created_by: INT
      updated_at: DATETIME
      updated_by: INT
    }
    materials |o.l.o{ mapping_material_requests_materials
    materials |o..o{ material_continuous_requests
    materials |o..o{ material_continuous_request_shots
  }
  material_continuous_requests }o..o| boxes
  material_requests }o..o| boxes
}
frame "note ERD" {
  entity "note_maintenance_quantites" {
    + note_maintenance_quantity_id: INT <<Gen>>
    ==
    # note_maintenance_id: INT
    # item_id: INT
    stock_quantity: INT
    loss_quantity: INT
    sales_quantity: INT
    actual_delivery_quantity: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "note_maintenances" {
    + note_maintenance_id: INT <<Gen>>
    ==
    # box_id: INT
    maintenance_date: DATE
    prev_note_maintenance_id: INT
    collect_amount: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "note_role_groups" {
    + note_role_group_id: INT <<Gen>>
    ==
    name: VARCHAR
    sort_order: INT
    created_at: DATETIME
    created_by: INT
  }
  entity "note_roles" {
    + note_role_id: INT <<Gen>>
    ==
    * name: VARCHAR
    description: VARCHAR
    sort_order: INT
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "mapping_note_role_groups_note_roles" {
    + note_role_group_id: INT
    + note_role_id: INT
    ==
  }
  entity "mapping_note_users_note_roles" {
    + note_user_id: INT
    + note_role_id: INT
    + contract_id: INT
    ==
    created_at: DATETIME
    created_by: INT
  }
  entity "note_users" {
    + id: INT <<Gen>>
    ==
    name: VARCHAR
    email: VARCHAR
    encrypted_password: VARCHAR
    # company_id: MEDIUMINT
    contract_id: INT
    contact_id: INT
    reset_password_token: VARCHAR
    reset_password_sent_at: DATETIME
    remember_created_at: DATETIME
    sign_in_count: INT
    current_sign_in_at: DATETIME
    last_sign_in_at: DATETIME
    current_sign_in_ip: VARCHAR
    last_sign_in_ip: VARCHAR
    password_salt: VARCHAR
    is_force_change_password: TINYINT
    can_edit_permission: TINYINT
    is_backdoor: TINYINT
    default_password: VARCHAR
    created_at: DATETIME
    updated_at: DATETIME
  }
  note_users |o..o{ mapping_note_users_note_roles
  note_roles |o..o{ mapping_note_users_note_roles
  note_maintenances |o..o{ note_maintenance_quantites
  note_role_groups |o..o{ mapping_note_role_groups_note_roles
  note_roles |o..o{ mapping_note_role_groups_note_roles
}
frame "invoce ERD" {
  entity "invoice_detail_spots" {
    + invoice_detail_spot_id: INT <<Gen>>
    ==
    # contract_id: INT
    yearmonth: INT
    text: VARCHAR
    from: DATE
    to: DATE
    invoice_type: TINYINT
    unit_price: INT
    amount: SMALLINT
    tax_class: TINYINT
    source_id: INT
    created_at: DATETIME
    created_by: INT
  }
  entity "invoice_details" {
    + invoice_detail_id: INT <<Gen>>
    ==
    # invoice_id: INT
    text: VARCHAR
    invoice_type: TINYINT
    from: DATE
    to: DATE
    unit_price: INT
    amount: SMALLINT
    tax_class: TINYINT
    tax_rate: DECIMAL
    source_id: INT
    created_at: DATETIME
    created_by: INT
  }
  entity "invoice_note_templates" {
    + invoice_note_template_id: INT <<Gen>>
    ==
    # contract_id: INT
    sort_order: TINYINT
    note: MEDIUMTEXT
    yearmonth_from: INT
    yearmonth_to: INT
    created_at: DATETIME
    created_by: INT
  }
  entity "invoice_notes" {
    + invoice_note_id: INT <<Gen>>
    ==
    # invoice_id: INT
    note: MEDIUMTEXT
    created_at: DATETIME
    created_by: INT
  }
  entity "invoice_payments" {
    + invoice_payment_id: INT <<Gen>>
    ==
    # invoice_id: INT
    payment_date: DATE
    amount: MEDIUMINT
    memo: MEDIUMTEXT
    is_import: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "invoice_send_log_details" {
    + invoice_send_log_detail_id: INT <<Gen>>
    ==
    # invoice_send_log_id: INT
    # invoice_id: INT
    created_at: DATETIME
    created_by: INT
  }
  entity "invoice_send_logs" {
    invoice_send_log_id: INT <<Gen>>
    ==
    sent_at: DATETIME
    # company_id: INT
    created_by: INT
  }
  entity "invoices" {
    + invoice_id: INT <<Gen>>
    ==
    disp_invoice_id: VARCHAR
    # contract_id: MEDIUMINT
    yearmonth: INT
    due_date: DATE
    fix_flag: TINYINT
    total_amount: INT
    payment_type: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  invoices |o..o{ invoice_details
  invoices |o.l.o{ demand_letter_send_logs
  invoices |o..o{ invoice_notes
  invoices |o.r.o{ invoice_payments
  invoices |o.d.o{ invoice_send_log_details
  invoice_send_logs |o..o{ invoice_send_log_details
}
frame "maintenance ERD" {
  entity "maintenance_schedules" {
    + maintenance_schedule_id: INT <<Gen>>
    ==
    # contract_id: MEDIUMINT
    maintenance_date: DATE
    maintenance_type_id: INT
    is_without_delivery_sheet: TINYINT
    is_without_maintenance: TINYINT
    is_without_suggest: TINYINT
    is_notified: TINYINT
    is_extra_request: TINYINT
    comment: VARCHAR
    inner_comment: VARCHAR
    created_at: DATETIME
    created_by: INT
  }
  entity "maintenance_schedule_available_hours" {
    + id: INT <<Gen>>
    ==
    specified_time_start: TIME
    specified_time_end: TIME
    # maintenance_schedule_id: INT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "maintenance_schedule_extents" {
    + maintenance_schedule_id: INT
    + box_id: INT
    ==
    comment: VARCHAR
    is_request_desired: TINYINT
    one_plate: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "maintenance_handies" {
    + maintenance_id: INT
    ==
    comment: TEXT
    start_at: DATETIME
    end_at: DATETIME
    check_loss_quantity1: TINYINT
    check_loss_quantity2: TINYINT
    check_takeout_quantity1: TINYINT
    check_takeout_quantity2: TINYINT
    created_at: DATETIME
    created_by: INT
    updated_at: DATETIME
    updated_by: INT
  }
  entity "maintenance_handy_logs" {
    + maintenance_handy_log_id: INT <<Gen>>
    ==
    # maintenance_id: INT
    params: TEXT
    created_at: DATETIME
    created_by: INT
  }
  entity "maintenance_handy_users" {
    + maintenance_handy_user_id: INT
    ==
    name: VARCHAR
    token: VARCHAR
    expire_date: DATETIME
    sign_in_count: INT
    last_sign_in_at: DATETIME
    created_at: DATETIME
    created_by: INT
    undated_at: DATETIME
    updated_by: INT
  }
  entity "maintenance_types" {
    + maintenance_type_id: INT <<Gen>>
    ==
    service_type: TINYINT
    maintenance_type_name: VARCHAR
    maintenance_type_note_name: VARCHAR
    is_without_delivery_sheet: TINYINT
    is_without_maintenance: TINYINT
    is_without_suggest: TINYINT
    sort_order: INT
    created_at: DATETIME
    created_by: INT
  }
  entity "maintenance_upper_limits" {
    + maintenance_upper_limit_id: INT <<Gen>>
    ==
    service_type: TINYINT
    upper_limit: SMALLINT
    unit: VARCHAR
    created_at: DATETIME
    updated_at: DATETIME
  }
  entity "box_payments" {
    + maintenance_id: INT
    ==
    used_amount: MEDIUMINT
    collect_amount: MEDIUMINT
    collect_amount_cash: MEDIUMINT
    collect_amount_appli_web: MEDIUMINT
    collect_amount_appli_native: MEDIUMINT
    collect_amount_ic: MEDIUMINT
    uncollect_amount: MEDIUMINT
    created_at: DATETIME
    created_by: INT
  }
  maintenance_schedules |o..o{ schedule_adjustment_requests
  maintenance_schedules ||..o{ maintenance_schedule_available_hours
  maintenance_schedules ||..o| maintenance_schedule_extents
  maintenance_schedules }|..|| maintenance_types
  maintenance_schedules |o..o{ material_requests
}

companies |o..o{ note_users
companies |o..o{ note_maintenances
note_users |o..o{ schedule_adjustment_requests
contracts |o..o{ office_addon_orders
contracts |o..o{ office_plan_orders
contracts |o..o{ plan_revision_logs
contracts |o..o| plan_revision_send_logs
plans |o.r.o{ mapping_contracts_addons
plans |o.r.o{ mapping_contracts_plans
invoices }o.d.o{ contracts
boxes }o.d.o| contracts
contracts |o.d.o{ office_plan_orders
contracts |o.d.o{ maintenance_schedules
contracts |o.d.o{ office_addon_orders
contracts |o.d.o{ application_send_logs
contracts |o.d.o{ demand_letter_send_logs
contracts |o.d.o{ schedule_adjustment_requests
contracts |o.d.o{ schedule_mail_send_logs
contracts |o.d.o{ statement_of_delivery_send_logs
contracts |o.d.o{ tft_donation_requests
contracts |o.d.o{ invoice_detail_spots
contracts |o.d.o{ invoice_note_templates
contracts |o.d.o{ mapping_contracts_note_restrictable_functions
contracts |o.d.o{ mapping_note_users_note_roles
companies |o.d.o{ invoice_send_logs
contracts |o.d.o{ plan_revision_logs
contracts |o.d.o| plan_revision_send_logs
items ||.u.o{ mapping_menus_items
menus ||..o{ item_requests
boxes }o.d.o| contracts
items ||.u.o{ mapping_menus_items
maintenance_schedules ||..o{ box_maintenances
maintenance_schedules ||..o{ box_prepares
maintenance_schedules ||..o| box_payments
maintenance_schedules ||..o{ box_orders
maintenance_schedules ||..o{ box_stocks
maintenance_schedules ||..o{ box_achievements
maintenance_schedules ||..o{ item_requests
maintenance_schedule_extents |o.l.o| boxes
items |o..o{ note_maintenance_quantites
items |o..o{ mapping_item_requests_items
boxes |o..o{ material_continuous_requests
boxes |o..o{ material_continuous_request_shots
boxes |o..o{ material_requests
items |o.u.o{ depot_orders
items |o.u.o{ depot_receiveds
items |o.u.o{ depot_stocks
invoice_details |o..o{ journalizings
companies |o..|{ invoice_send_logs
' --------------------------------

statement_of_delivery_send_logs |o..o{ statement_of_delivery_send_log_details
maintenance_handies |o..|{ maintenance_handy_logs


@enduml
